name: Deploy to Hugging Face (Develop)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt huggingface-hub

      - name: Run Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          SQL_URI: ${{ secrets.SQL_URI }}
        run: |
          pytest

      - name: Authenticate with Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_PERSONAL_ACCESS_TOKEN }}
        run: |
          mkdir -p ~/.huggingface
          echo "${HF_TOKEN}" > ~/.huggingface/token
          chmod 600 ~/.huggingface/token

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
      - name: Set Hugging Face Remote with Token
        env:
          HF_PERSONAL_ACCESS_TOKEN: ${{ secrets.HF_PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote set-url origin https://${{ secrets.HF_PERSONAL_ACCESS_TOKEN }}@huggingface.co/spaces/SooryaOmeg/HHMS

      - name: Push to Hugging Face Space
        run: |
          git push origin develop
