name: Deploy to Hugging Face

on:
  push:
    branches:
      - main  # Triggers the workflow on every push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the type of virtual machine to use

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          # Add your testing framework command here
          pytest

      - name: Build Docker image
        run: docker build -t my-flask-app .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Hugging Face Docker registry
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: |
          echo $HF_API_TOKEN | docker login huggingface.co -u <your-huggingface-username> --password-stdin

      - name: Push Docker image to Hugging Face
        run: |
          docker tag my-flask-app huggingface.co/<your-huggingface-username>/<repo-name>:latest
          docker push huggingface.co/<your-huggingface-username>/<repo-name>:latest
