name: Deploy to Hugging Face

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt huggingface-hub

      - name: Run Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          SQL_URI: ${{ secrets.SQL_URI }}
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Hugging Face Hub
        run: pip install huggingface-hub

      - name: Log in to Hugging Face
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: huggingface-cli login --token $HF_API_TOKEN

      - name: Upload Code or Model to Hugging Face
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: |
          git remote add hf https://huggingface.co/SooryaOmeg/HHMS
          git push hf main
          # python -c "from huggingface_hub import HfApi, Repository
          # repo_id = 'spaces/SooryaOmeg/HHMS'
          # repo = Repository(local_dir='./', clone_from=repo_id, use_auth_token='$HF_API_TOKEN')
          # repo.push_to_hub()
          # "
