name: Deploy to Hugging Face

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt huggingface-hub

      - name: Run Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          SQL_URI: ${{ secrets.SQL_URI }}
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install Hugging Face Hub
        run: pip install huggingface-hub
        
      - name: Configure Git and Token
        env:
          HF_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          git remote remove origin || true
          
          # Add new origin with token in the URL
          git remote add origin "https://SooryaOmeg:${HF_TOKEN}@huggingface.co/spaces/SooryaOmeg/HHMS"
          # git config pull.rebase false
          # git pull origin main
          
          # # Set up huggingface token for API access
          # mkdir -p ~/.huggingface
          # echo "${HF_TOKEN}" > ~/.huggingface/token
          # chmod 600 ~/.huggingface/token
          
          # # Push to Hugging Face
          # git push origin main || git push --force origin main
          git checkout -b temp-deploy
           git add .
          git commit -m "Update from GitHub Actions" || true
          
          # Force push to Hugging Face
          git push --force origin temp-deploy:main
