name: Deploy to Hugging Face
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt huggingface-hub
          
      - name: Run Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          SQL_URI: ${{ secrets.SQL_URI }}
        run: |
          pytest
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install
          
      - name: Install Hugging Face Hub
        run: pip install huggingface-hub
        
      - name: Configure Git and Deploy
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}  # Kept original secret name
        run: |
          # Configure git
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Initialize Git LFS
          git lfs install
          git lfs track "*.pt"
          git lfs track "*.pth"
          git lfs track "*.bin"
          git lfs track "*.onnx"
          git lfs track "*.h5"
          
          # Clean any existing git state
          git clean -fdx
          
          # Initialize new git repository
          rm -rf .git
          git init
          
          # Add all files and LFS files
          git add .gitattributes
          git add .
          git commit -m "Initial commit from GitHub Actions"
          
          # Add Hugging Face as remote and push
          git remote add origin https://SooryaOmeg:${HF_API_TOKEN}@huggingface.co/spaces/SooryaOmeg/HHMS
          git push --force origin master:main
          
          # Set up huggingface token for API access
          mkdir -p ~/.huggingface
          echo "${HF_API_TOKEN}" > ~/.huggingface/token
          chmod 600 ~/.huggingface/token
