name: Deploy to Hugging Face

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt huggingface-hub

      - name: Run Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          SQL_URI: ${{ secrets.SQL_URI }}
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Hugging Face Hub
        run: pip install huggingface-hub

      - name: Log in to Hugging Face
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: huggingface-cli login --token $HF_API_TOKEN

      - name: Setup Git Config
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
      - name: Install Hugging Face CLI
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub
        
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          echo "Pushing directly to Hugging Face..."
          
          # Remove origin to avoid confusion
          git remote remove origin
          
          # Add Hugging Face as new origin with token
          git remote add origin "https://$HF_TOKEN@huggingface.co/spaces/SooryaOmeg/HHMS"
          
          # Force push all content
          git push -f origin main:ma
