name: Deploy to Hugging Face

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt huggingface-hub

      - name: Run Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          SQL_URI: ${{ secrets.SQL_URI }}
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install Hugging Face Hub
        run: pip install huggingface-hub
        
      - name: Configure Git and Token
        env:
          HF_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Set up token for git authentication
          git config --global credential.helper store
          echo "https://USER:${HF_API_TOKEN}@huggingface.co" > ~/.git-credentials
          chmod 600 ~/.git-credentials
          
          # Set up huggingface token
          mkdir -p ~/.huggingface
          echo "${HF_API_TOKEN}" > ~/.huggingface/token
          chmod 600 ~/.huggingface/token
          
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: |
          git remote set-url origin https://SooryaOmeg:$HF_API_TOKEN@huggingface.co/spaces/SooryaOmeg/HHMS
          git push origin main
